### ISSUE TITLE
если у двух игроков есть сапфировая броня то крашится сервер

### ISSUE THREAD

**Issue by ffw299** [TriQue06/mythic-upgrades-1.20.x#113]
If two players in sapphire armor hit each other, then the server stops, and if in single player mode, then Minecraft crashes and the other player has to craft another armor, as well as when jade armor vs sapphire armor on 1.20.1 fabric with mods. 
If you are not Russian, here is the translation.
урон-damage
отравление-poisoning
отключается сервер-disabling the server
also with the first option that is with the same armor damage is infinitely reflected 
![Без имени](https://github.com/user-attachments/assets/f01aee59-f5ea-4fe0-b7a9-3e56c9a3644f)

**Comment by CyberSteve777** [comment]
А какая версия мода?

**Comment by CyberSteve777** [comment]
Закрываю поскольку нет ответа, если будут вопросы - есть дискорд, ну или еще один репорт кинете
