### ISSUE TITLE
How to make equipment?

### ISSUE THREAD

**Issue by pil0lo** [TriQue06/mythic-upgrades-1.20.x#115]
I can only see the decision block, how do I make the equipment?

**Comment by CyberSteve777** [comment]
You'll need smithing templates and smithing table

**Comment by pil0lo** [comment]
Is it possible to strengthen it with a decision block??

**Comment by pil0lo** [comment]
Can I craft equipment with this crystal block???
I haven't seen the ore block.

![1](https://github.com/user-attachments/assets/38f3df55-c1e0-482b-9775-a392e3c84a20)

**Comment by CyberSteve777** [comment]
For both questions answer is no. For Sapphire if you are playing Prominence, look into warped forests

**Comment by pil0lo** [comment]
Aquamarine "lcy"? Is it snow area?

**Comment by pil0lo** [comment]
Aquamarine Nether? Near the Soul Sand?

**Comment by pil0lo** [comment]
What is the Arcane Aura effect?

**Comment by pil0lo** [comment]
The poison effect from the Poison Thorn effect of the Peridot equipment set is not applied.

**Comment by CyberSteve777** [comment]
@pil0lo check if your enemy doesn't have immunity to poison

**Comment by pil0lo** [comment]
Where can I get a sapphire template? I haven't gotten a sapphire template yet.

The photos were taken in creative mode.
![1](https://github.com/user-attachments/assets/e320f97a-8777-4e03-9b7c-22e800c57018)

**Comment by CyberSteve777** [comment]
As stated on mod sites, in nether fortresses

**Comment by CyberSteve777** [comment]
Closing this issue since aswered questions. If there will be more, ask in discord server linked in mod pages or open another issue
