### ISSUE TITLE
PoisonousThornsEffect spams stdout null to the console

### ISSUE THREAD

**Issue by kaleabelgas** [TriQue06/mythic-upgrades-1.20.x#116]
As title says, wearing the full peridot armor or drinking the peridot potion floods the server console with persistent and endless streams of 
`[05:00:50] [Server thread/INFO]: [net.trique.mythicupgrades.effect.PoisonousThornsEffect] null class_1531['Armor Stand'/1073, l='ServerLevel[People]', x=-11.50, y=69.00, z=23.50]`
 
![image](https://github.com/user-attachments/assets/235e19bf-dcec-4e6d-956c-58178ea14a23)

In this case an armor stand is wearing the armor. It is the same for players. The only solution I've found is to not use the armor nor drink the potion.

Server version: Fabric 1.21.1
Mod version: mythicupgrades-4.1.4+mc1.21.jar

**Comment by CyberSteve777** [comment]
Thanks for report, will be fixed in next update!

**Comment by CyberSteve777** [comment]
Fixed in 4.2.0
