### ISSUE TITLE
Server crashes if 2 players with Sapphire armor hit eachother.

### ISSUE THREAD

**Issue by rudiPT** [TriQue06/mythic-upgrades-1.20.x#121]
Minecraft Version:
1.20.1

Fabric Version:
0.16.8

Mod Version:
2.3.2

If one of the players remove the armor the server won't crash. I'm guessing the problem is with the Damage Deflection effect.

[crash-2024-11-02_16.19.34-server.txt](https://github.com/user-attachments/files/17607648/crash-2024-11-02_16.19.34-server.txt)

**Comment by CyberSteve777** [comment]
This issue was fixed in 2.4.0, please update to this version atleast
