### ISSUE TITLE
Typo in Jade Upgrade duplication recipe prevents it from loading

### ISSUE THREAD

**Issue by DJChaos42** [TriQue06/mythic-upgrades-1.20.x#2]
### Issue
In the Jade Upgrade Smithing Template duplication recipe, the template ingredient is referred to as "minecraft:jade_upgrade_smithing_template" instead of "mythicupgrades:jade_upgrade_smithing_template". This causes an error and prevents the recipe from loading.

### Testing Environment

- Mod Loader: Fabric 0.14.22
- Mythic Upgrades version: mc1.20.1-2.2.2

**Comment by CyberSteve777** [comment]
Hello! This is a known issue and it will be fixed in next update. Stay tuned!

**Comment by TriQue06** [comment]
Will be fixed with next release, it will be released this week.
