### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by linaraincalzando** [TriQue06/mythic-upgrades-1.20.x#41]
[crash.txt](https://github.com/TriQue06/mythic-upgrades-1.20.x/files/12906736/crash.txt)

Almost immediately crashes. Are there any mods, like Forgero that Mythic Upgrades is not compatible with?

**Comment by CyberSteve777** [comment]
Fixed in #44

**Comment by CyberSteve777** [comment]
Actually, not fully, Origins' dev is required to rename old ModToolMaterials in his compat class

**Comment by linaraincalzando** [comment]
Does that mean I need to reach out to the Origins dev to loop them in? Or is that being handled on your end?

**Comment by CyberSteve777** [comment]
@linaraincalzando I have already told them in their bug report channel in discord, so it's on their end now

**Comment by CyberSteve777** [comment]
Oops, crash with origins was on our side, the fix will be available in next update

**Comment by TriQue06** [comment]
fixed
