### ISSUE TITLE
Mod doesn´t work on latest fabric version

### ISSUE THREAD

**Issue by SpiritOTHawk** [TriQue06/mythic-upgrades-1.20.x#54]

**Comment by CyberSteve777** [comment]
@SpiritOTHawk Can you provide crash-report and `latest.log` files pls

**Comment by SpiritOTHawk** [comment]
[latest.log](https://github.com/TriQue06/mythic-upgrades-1.20.x/files/13055743/latest.log)

**Comment by CyberSteve777** [comment]
It's an issue with origins, fix is already done and will be available in next update

**Comment by TriQue06** [comment]
fixed
