### ISSUE TITLE
Haste effect sometimes doesn't go away

### ISSUE THREAD

**Issue by 03-JS** [TriQue06/mythic-upgrades-1.20.x#61]
The haste effect the Ruby items provide seems to be a bit bugged as it sometimes won't go away if you hold a different item from the mod. This seems to happen with almost every item I've tried. You can even get the effect when you're not holding anything if you previously held a different item from the mod.

![2023-11-11_14 26 54](https://github.com/TriQue06/mythic-upgrades-1.20.x/assets/107844615/256d8a4d-6561-4671-b253-6ece8e93a3b1)
![2023-11-11_14 27 13](https://github.com/TriQue06/mythic-upgrades-1.20.x/assets/107844615/cf2a3b44-892c-479a-a4b1-7bb71f0b13b5)

**Comment by CyberSteve777** [comment]
Hello! Yeah, I noticed that, and fixed in dev environment. Will be fixed in next release
